from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, CallbackQueryHandler, MessageHandler, filters, ContextTypes

TOKEN = "8048297200:AAEIwC9jYEXk8kE89Ciw_8uDZ7BIUK9mx-Q"

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Inicia o bot e exibe os objetivos de treino"""
    keyboard = [
        [InlineKeyboardButton("Sou Iniciante", callback_data="objetivo_Iniciante")],
        [InlineKeyboardButton("Treinar Aberturas", callback_data="objetivo_Aberturas")],
        [InlineKeyboardButton("Treinar Estratégia Meio-Jogo", callback_data="objetivo_MeioJogo")],
        [InlineKeyboardButton("Treinar Finais", callback_data="objetivo_Finais")],
        [InlineKeyboardButton("Treinar Tática", callback_data="objetivo_Tática")],
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    await update.message.reply_text("🎯 Qual seu objetivo no xadrez?", reply_markup=reply_markup)

async def button(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Gerencia as respostas dos botões"""
    query = update.callback_query
    await query.answer()

    data = query.data

    if data.startswith("objetivo_"):
        objetivo = data.split("_")[1]
        context.user_data["objetivo"] = objetivo  # Salva o objetivo do usuário

        if objetivo == "Iniciante":
            await query.message.reply_text("⏳ Quantas horas por dia você pode treinar?")
            context.user_data["esperando_horas"] = True  # Pula a pergunta de rating
        else:
            await query.message.reply_text("📊 Qual é o seu rating atual?")
            context.user_data["esperando_rating"] = True  # Aguarda a resposta do rating

async def recebe_mensagem(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Recebe a resposta do usuário e gera o treino"""
    texto = update.message.text

    if context.user_data.get("esperando_rating"):
        context.user_data["rating"] = int(texto)  # Converte para número
        del context.user_data["esperando_rating"]  # Remove a flag
        await update.message.reply_text("⏳ Quantas horas por dia você pode treinar?")
        context.user_data["esperando_horas"] = True  # Agora espera a resposta de horas
        return

    if context.user_data.get("esperando_horas"):
        context.user_data["horas"] = texto
        del context.user_data["esperando_horas"]  # Remove a flag

        objetivo = context.user_data.get("objetivo", "Desconhecido")
        rating = context.user_data.get("rating", None)
        horas = context.user_data.get("horas", "N/A")

        treino = gerar_treino(objetivo, rating, horas)  # Chama a função que gera o treino

        await update.message.reply_text(f"✅ Aqui está o seu treino:\n\n{treino}")

def gerar_treino(objetivo, rating, horas):
    """Gera o treino baseado no objetivo e na faixa de rating"""

    if objetivo == "Iniciante":
        return f"🏆 **Treinamento de Xadrez para Iniciantes (0 a 999 de Rating)** 🏆\n\n👑 **Objetivo do Treinamento**: Se você é iniciante, o primeiro passo é aprender as regras e os conceitos básicos do jogo! Aqui está o que você deve dominar:\n\n1️⃣ **Regras Básicas**:\n\n📍 **Conheça o Tabuleiro**\nEntenda as colunas, linhas e casas! 🧩\n\n♟️ **Movimento das Peças**\nSaiba como cada peça se move: Rei, Dama, Cavalo, Bispo, Torre e Peão! 🔄\n\n🛡️ **Como as Peças Capturam e Como se Defendem**\nEntenda a mecânica da captura e a importância da defesa! ⚔️🛡️\n\n⚡ **Xeque**\nO que fazer quando seu Rei está ameaçado? 🏃‍♂️\n\n🔪 **Xeque-Mate**\nComo dar o golpe final no adversário! 🏆\n\n2️⃣ **Movimentos Especiais**:\n\n🔄 **Promoção do Peão**\nQuando o peão chegar ao final do tabuleiro, ele pode se transformar em uma peça poderosa! 💥\n\n🔐 **Roque**\nProteja seu Rei e desenvolva suas peças ao mesmo tempo! 👑🤝\n\n🕵️ **Captura 'En Passant'**\nUma captura especial que pode surpreender seu adversário! 👀\n\n3️⃣ **Tipos de Empate**:\n\n🔄 **Empate por Repetição de Movimentos**\nQuando a mesma posição se repete três vezes, o jogo empata! 🔁\n\n⚖️ **Empate por Stalemate (Afogado)**\nO Rei não está em xeque, mas não pode fazer nenhum movimento legal. 🤔\n\n🎮 **Pratique Muito!**\nJogue partidas sem limite de tempo para ganhar experiência!\nUse o chess.com ou lichess.org para jogar online gratuitamente.\nTambém pode praticar jogando com amigos em um tabuleiro de xadrez físico. 🧩♟️\n\n📚 **Dica Extra**:\nBaixe o nosso Ebook 'Aprenda a Jogar Xadrez Online' da página **Xadrez com Z**! Nele, você aprenderá sobre a história do xadrez, regras básicas, conceitos e tipos de empate. Acesse o link abaixo e confira. 📖\n\n🔗 [https://xadrezcomz.wixsite.com/xadrez-com-z/general-clean](#)\n\n💡 **Dica para Progresso**:\nDedique pelo menos 20 minutos por dia para estudar e praticar! ⏰\nRevise sempre os movimentos das peças e os conceitos de Xeque e Xeque-Mate! 🔍\nBoa sorte, e que sua jornada no xadrez seja incrível! 🌟♟️"

    if rating is None:
        return "⚠️ Algo deu errado. Por favor, reinicie o bot com /start."

    if objetivo == "Aberturas":
        if rating < 1000:
            return f"📌 **Treino de Aberturas (Rating: 0-1000)**\n- [Iniciante (0-1000) 🌱♟️\n\n📝 **Objetivo**: Entender os princípios básicos das aberturas.\n\n🎓 **Prática**:\n- Aprenda Abertura de Peão de Rei (1. e4) e Abertura de Peão de Dama (1. d4).\n\n🔑 **Princípios**:\n- Controle do centro ♟️, desenvolvimento rápido das peças 🚀 e segurança do Rei 👑.\n\n⏱️ **Atividade**:\n- Jogue partidas rápidas de 5 minutos online 💻, priorizando o desenvolvimento das peças. 🏃‍♂️\n\n⚠️ **Dica**:\n- Evite mover os mesmos peões várias vezes na abertura, isso pode perder tempo ⏳.\n\n📚 **Livro recomendado**:\n- 'Xadrez Para Crianças' de Murray Chandler 📖]"
        elif rating < 1200:
            return f"📌 **Treino de Aberturas (Rating: 1000-1200)**\n- [Intermediário (1000-1200) 🧠♟️\n\n📝 **Objetivo**: Aprender e praticar aberturas mais complexas e suas ideias.\n\n🎓 **Prática**:\n- Aprenda Abertura Italiana (1. e4 e5 2. Nf3 Nc6 3. Bc4) e Defesa Siciliana (1. e4 c5).\n\n🔑 **Princípios**:\n- Controle do centro ♟️, desenvolva as peças rapidamente 🚀 e mantenha o Rei seguro 👑.\n\n⏱️ **Atividade**:\n- Jogue partidas de 10 minutos online ⏳, aplicando as aberturas que aprendeu.\n\n⚠️ **Dica**:\n- Não saia movendo peças sem pensar, cada movimento deve ter um propósito. 💡\n\n📚 **Livro recomendado**:\n- 'Xadrez Para Leigos' de James Eade 📖]"
        elif rating < 1400:
            return f"📌 **Treino de Aberturas (Rating: 1200-1400)**\n- [Intermediário Avançado (1200-1400) 🎯♟️\n\n📝 **Objetivo**: Aprofundar no estudo de aberturas e explorar os primeiros conceitos do meio-jogo.\n\n🎓 **Prática**:\n- Aprenda Abertura Espanhola (1. e4 e5 2. Nf3 Nc6 3. Bb5) e Defesa Caro-Kann (1. e4 c6).\n\n🔑 **Princípios**:\n- Controle de espaço, centro e atividade das peças ⚡.\n\n⏱️ **Atividade**:\n- Jogue partidas de 10-15 minutos online 🕹️, experimentando as aberturas estudadas e desenvolvendo suas peças.\n\n⚠️ **Dica**:\n- Fique atento às ameaças do adversário e procure jogadas de preparação para o meio-jogo. 🧐\n\n📚 **Livro recomendado**:\n- 'O Livro Completo do Xadrez' de Garry Kasparov 📚]"
        elif rating < 1600:
            return f"📌 **Treino de Aberturas (Rating: 1400-1600)**\n- [Avançado (1400-1600) 💡♟️\n\n📝 **Objetivo**: Melhorar o conhecimento das aberturas e começar a desenvolver o meio-jogo com mais profundidade.\n\n🎓 **Prática**:\n- Estude Abertura Inglesa (1. c4) e Defesa de Benoni (1. d4 Nf6 2. c4 c5).\n\n🔑 **Princípios**:\n- Controle de centro e criação de planos estratégicos 🧠.\n\n⏱️ **Atividade**:\n- Jogue partidas de 15-20 minutos online ⏰, foque na compreensão do meio-jogo e no desenvolvimento das peças.\n\n⚠️ **Dica**:\n- Tenha paciência e não apresente vantagens sem entender a posição. 🧘\n\n📚 **Livro recomendado**:\n- 'Manual de Xadrez' de Bobby Fischer 📖]"
        elif rating < 1800:
            return f"📌 **Treino de Aberturas (Rating: 1600-1800)**\n- [Muito Avançado (1600-1800) 🏅♟️\n\n📝 **Objetivo**: Aprofundar-se nas aberturas e no estudo de estruturas de peões.\n\n🎓 **Prática**:\n- Estude Abertura Ruy Lopez (1. e4 e5 2. Nf3 Nc6 3. Bb5) e Defesa Grünfeld (1. d4 Nf6 2. c4 g6).\n\n🔑 **Princípios**:\n- Avaliação de posições, construção de planos e simplificação da posição quando vantajoso ⚖️.\n\n⏱️ **Atividade**:\n- Jogue partidas de 20-30 minutos online 🕹️, praticando o planejamento estratégico e os sacrifícios calculados.\n\n⚠️ **Dica**:\n- Analise as partidas após jogar, tentando entender os erros e os bons movimentos. 🔍\n\n📚 **Livro recomendado**:\n- 'Xadrez: A Arte da Guerra' de Sun Tzu e Garry Kasparov 📚]"
        elif rating < 2000:
            return f"📌 **Treino de Aberturas (Rating: 1800-2000)**\n- [Especialista (1800-2000) 💪♟️\n\n📝 **Objetivo**: Refinar o conhecimento sobre as aberturas e aprofundar a análise tática e estratégica.\n\n🎓 **Prática**:\n- Estude Abertura do Rei (1. e4 e5 2. Nf3 Nc6 3. Bc4) e Defesa Siciliana (1. e4 c5).\n\n🔑 **Princípios**:\n- Agir com precisão, buscar a excelência na execução das aberturas e explorar posições complexas 🤔.\n\n⏱️ **Atividade**:\n- Jogue partidas de 30 minutos online 🕰️, sempre analisando cada movimento e buscando uma execução impecável.\n\n⚠️ **Dica**:\n- Busque sempre melhorar suas táticas e desenvolva uma forte preparação de aberturas para alcançar grandes resultados. 🌟\n\n📚 **Livro recomendado**:\n- 'Xadrez: Teoria e Prática' de Aaron Nimzowitsch 📖]"
        elif rating < 2200:
            return f"📌 **Treino de Aberturas (Rating: 2000-2200)**\n- [Mestre (2000-2200) 🏆♟️\n\n📝 **Objetivo**: Aperfeiçoar a execução de aberturas avançadas e o domínio da técnica no meio-jogo.\n\n🎓 **Prática**:\n- Estude Defesa Francesa (1. e4 e6) e Defesa Escandinava (1. e4 d5).\n\n🔑 **Princípios**:\n- Busque sempre posições vantajosas e utilize jogadas altamente calculadas 🔢.\n\n⏱️ **Atividade**:\n- Jogue partidas de 30-40 minutos online 🕰️, trabalhando sua transição para o meio-jogo e a conclusão das fases táticas e estratégicas.\n\n⚠️ **Dica**:\n- Preste atenção nos detalhes das suas partidas e refine sua compreensão de aberturas e jogadas intermediárias. 🔎\n\n📚 **Livro recomendado**:\n- 'Xadrez: O Jogo Completo' de Garry Kasparov 📖]"
        else:
            return f"📌 **Treino de Aberturas (Rating: 2200+)**\n- [Grande Mestre (2200+) 🏅♟️\n\n📝 **Objetivo**: Aperfeiçoar o entendimento das aberturas e das transições para o meio-jogo e finais.\n\n🎓 **Prática**:\n- Estude Abertura Inglesa (1. c4) e Defesa Catalã (1. d4 Cf6 2. c4 e6).\n\n🔑 **Princípios**:\n- Dominar as transições de fases, sendo capaz de manipular qualquer posição com fluência 🤖.\n\n⏱️ **Atividade**:\n- Jogue partidas longas de 40 minutos ou mais, sempre buscando perfeição nas fases iniciais e transição para o meio-jogo. 🕰️\n\n⚠️ **Dica**:\n- Analise profundamente suas partidas e as de outros Mestres, sempre buscando entender cada movimento estratégico. 🔍\n\n📚 **Livro recomendado**:\n- 'Minha Grande Aventura no Xadrez' de Magnus Carlsen 📖]"

    if objetivo == "MeioJogo":
        if rating < 1000:
            return f"📌 **Treino de Meio Jogo (Rating: 0-1000)**\n- [Iniciante (0-999) 🌱♟️\n\n📝 **Objetivo**: Entender os conceitos básicos do meio-jogo, focando no desenvolvimento das peças e na segurança do Rei.\n\n🎓 **Prática**:\n- Explore o desenvolvimento de peças e a importância de manter o Rei seguro.\n- Aplique táticas simples como garfos e cravadas.\n\n🔑 **Princípios**:\n- Não deixe peças soltas, desenvolva suas peças rapidamente e busque segurança no Rei 👑.\n\n⏱️ **Atividade**:\n- Jogue partidas rápidas de 5 minutos online 🕒, priorizando o desenvolvimento e evitando trocas desnecessárias.\n\n⚠️ **Dica**:\n- Não se apresse em fazer movimentos, pense nas ameaças do adversário e na sua defesa. 💡\n\n📚 **Livro recomendado**:\n- 'Xadrez Para Crianças' de Murray Chandler 📖]"
        elif rating < 1200:
            return f"📌 **Treino de Meio Jogo (Rating: 1000-1200)**\n- [Intermediário (1000-1200) 🧠♟️\n\n📝 **Objetivo**: Melhorar o entendimento das ideias no meio-jogo e começar a calcular táticas mais profundas.\n\n🎓 **Prática**:\n- Estude táticas como garfos, cravadas e ataques duplos.\n- Aprenda a identificar boas trocas e quando evitar uma troca desfavorável.\n\n🔑 **Princípios**:\n- Ataque ao Rei adversário 👑 e criação de ameaças no meio-jogo.\n- Proteja suas peças mais valiosas e aproveite o tempo para ameaçar as peças do oponente.\n\n⏱️ **Atividade**:\n- Jogue partidas de 10 minutos online ⏳, focando no desenvolvimento das táticas aprendidas.\n\n⚠️ **Dica**:\n- Cuidado com a falta de proteção em peças importantes, não deixe nada desprotegido. 🛡️\n\n📚 **Livro recomendado**:\n- 'Xadrez Para Leigos' de James Eade 📚]"
        elif rating < 1400:
            return f"📌 **Treino de Meio Jogo (Rating: 1200-1400)**\n- [Intermediário Avançado (1200-1400) 🎯♟️\n\n📝 **Objetivo**: Começar a focar em planos estratégicos no meio-jogo e entender a importância das trocas.\n\n🎓 **Prática**:\n- Estude como planejar ataques ao Rei adversário e a transição para o final.\n- Estude a importância da estrutura de peões e a vantagem de espaços abertos.\n\n🔑 **Princípios**:\n- Avalie a posição constantemente, pense em como melhorar suas peças e atacar pontos fracos adversários ⚔️.\n\n⏱️ **Atividade**:\n- Jogue partidas de 15 minutos online 🕰️, focando no controle de posição e táticas avançadas.\n\n⚠️ **Dica**:\n- Sempre tenha um plano, não jogue por jogadas aleatórias. 🎯\n\n📚 **Livro recomendado**:\n- 'O Jogo Completo de Xadrez' de Garry Kasparov 📖]"
        elif rating < 1600:
            return f"📌 **Treino de Meio Jogo (Rating: 1400-1600)**\n- [Avançado (1400-1600) 💡♟️\n\n📝 **Objetivo**: Aprofundar no cálculo de variantes e criar planos táticos e estratégicos no meio-jogo.\n\n🎓 **Prática**:\n- Estude táticas avançadas como sacrifícios e posições desequilibradas.\n- Aprenda a jogar em posições com material desequilibrado.\n\n🔑 **Princípios**:\n- Pense sempre em como desequilibrar a posição a favor do seu lado e identifique oportunidades de ataque 🏹.\n\n⏱️ **Atividade**:\n- Jogue partidas de 20 minutos online ⏳, praticando a escolha de táticas e avaliação estratégica.\n\n⚠️ **Dica**:\n- Use os princípios aprendidos para avaliar as vantagens do seu adversário e se posicionar para um contra-ataque. 🛡️\n\n📚 **Livro recomendado**:\n- 'Manual de Xadrez' de Bobby Fischer 📚]"
        elif rating < 1800:
            return f"📌 **Treino de Meio Jogo (Rating: 1600-1800)**\n- [Muito Avançado (1600-1800) 🏅♟️\n\n📝 **Objetivo**: Melhorar a capacidade de avaliar posições complexas e encontrar planos táticos e estratégicos profundos.\n\n🎓 **Prática**:\n- Estude ataques em posições fechadas e análise de estruturas de peões.\n- Estude como construir um ataque sólido e defender contra os ataques do adversário.\n\n🔑 **Princípios**:\n- Esteja sempre atento a ameaças diretas, aproveite a coordenação das peças para criar jogadas decisivas 🔐.\n\n⏱️ **Atividade**:\n- Jogue partidas de 25-30 minutos online 🕰️, tentando aplicar as táticas e construindo um plano de longo prazo.\n\n⚠️ **Dica**:\n- Quando o adversário faz um movimento, pense sempre no motivo dele ter feito aquilo, se foi uma defesa ou um ataque! 🎯\n\n📚 **Livro recomendado**:\n- 'A Arte da Guerra no Xadrez' de Garry Kasparov 📚]"
        elif rating < 2000:
            return f"📌 **Treino de Meio Jogo (Rating: 1800-2000)**\n- [Especialista (1800-2000) 💪♟️\n\n📝 **Objetivo**: Aprimorar as habilidades no cálculo de variantes complexas e transição para o final de maneira eficiente.\n\n🎓 **Prática**:\n- Estude ataques combinados e táticas para explorar a fragilidade da posição adversária.\n- Foque na busca de contra-ataques com base em fraquezas do oponente.\n\n🔑 **Princípios**:\n- Ao ter uma vantagem, procure simplificar e evitar complicações; ao estar em desvantagem, busque complicar a posição para gerar chances de contra-ataque 🔥.\n\n⏱️ **Atividade**:\n- Jogue partidas de 30-40 minutos online 🕰️, treinando como transitar para o final com vantagens.\n\n⚠️ **Dica**:\n- Quando sua posição está boa, simplifique as trocas. Quando estiver perdendo, lute pela complicação. ⚔️\n\n📚 **Livro recomendado**:\n- 'Xadrez: Teoria e Prática' de Aaron Nimzowitsch 📚]"
        elif rating < 2200:
            return f"📌 **Treino de Meio Jogo (Rating: 2000-2200)**\n- [Mestre (2000-2200) 🏆♟️\n\n📝 **Objetivo**: Aprofundar a compreensão das ideias de atacantes e defesas no meio-jogo, analisando posições altamente complexas.\n\n🎓 **Prática**:\n- Estude a coordenação das peças para ataques rápidos e como dificultar as transições para o final.\n- Aplique táticas de contra-jogo em posições com mais material.\n\n🔑 **Princípios**:\n- Crie uma ideia estratégica e foque na execução precisa de cada movimento 🔧.\n\n⏱️ **Atividade**:\n- Jogue partidas de 40-50 minutos online 🕰️, calculando táticas e estratégias complexas, refinando sua visão de jogo.\n\n⚠️ **Dica**:\n- Fique atento às oportunidades de atacar e sempre avalie a posição com um olhar crítico 👀.\n\n📚 **Livro recomendado**:\n- 'Como se Tornar um Grande Mestre' de Alexander Kotov 📖]"
        else:
            return f"📌 **Treino de Meio Jogo (Rating: 2200+)**\n- [Grande Mestre (2200+) 🏅♟️\n\n📝 **Objetivo**: Refinar a habilidade de criar planos estratégicos profundos e antecipar os movimentos do oponente com precisão.\n\n🎓 **Prática**:\n- Estude ataques posicionalmente profundos e a transição de materiais em finais complicados.\n- Foque em calcular variantes com precisão e otimizar a coordenação das suas peças para o ataque final.\n\n🔑 **Princípios**:\n- Busque a perfeição em cada movimento, sempre testando suas habilidades em partidas de alto nível 🔥.\n\n⏱️ **Atividade**:\n- Jogue partidas de 60 minutos ou mais, utilizando todo o tempo para examinar cada jogada minuciosamente 🕰️.\n\n⚠️ **Dica**:\n- Analise suas partidas de Mestres e Grandes Mestres, buscando entender as estratégias mais sofisticadas. 💎\n\n📚 **Livro recomendado**:\n- 'Minha Grande Aventura no Xadrez' de Magnus Carlsen 📖]"
        pass

    if objetivo == "Finais":
        if rating < 1000:
            return f"📌 **Treino de Finais (Rating: 0-1000)**\n- [Iniciante (0-999) 🌱♟️\n\n📝 **Objetivo**: Entender os conceitos básicos do final de jogo e aprender como ganhar finais simples.\n\n🎓 **Prática**:\n- Estude como ganhar um final de Rei e Peão contra Rei.\n- Aprenda as ideias básicas de oposição e como bloquear o Rei adversário.\n\n🔑 **Princípios**:\n- Pratique a técnica de promover um peão a uma dama e a importância de manter o Rei ativo.\n\n⏱️ **Atividade**:\n- Jogue finais simples de Rei e Peão contra Rei, focando na promoção do peão.\n\n⚠️ **Dica**:\n- Ao jogar finais simples, concentre-se em não deixar o Rei adversário bloquear o seu peão. 🚀\n\n📚 **Livro recomendado**:\n- 'Xadrez Para Crianças' de Murray Chandler 📖]"
        elif rating < 1200:
            return f"📌 **Treino de Finais (Rating: 1000-1200)**\n- [Intermediário (1000-1200) 🧠♟️\n\n📝 **Objetivo**: Melhorar o entendimento dos finais básicos e aprender a converter uma vantagem material em vitória.\n\n🎓 **Prática**:\n- Estude os finais de Torre contra Peão e como promover peões rapidamente.\n- Aprenda a calcular os finais de dois peões e como criar uma rede de defesa para o seu Rei.\n\n🔑 **Princípios**:\n- Use o Rei como uma peça ativa, ajudando a apoiar os peões na corrida para a promoção.\n\n⏱️ **Atividade**:\n- Pratique finais de Torre e Peão contra Rei.\n\n⚠️ **Dica**:\n- Não deixe seu Rei se afastar demais dos peões; ele deve estar sempre próximo para proteger e apoiar a promoção. 🛡️\n\n📚 **Livro recomendado**:\n- 'Finais de Xadrez' de John Nunn 📚]"
        elif rating < 1400:
            return f"📌 **Treino de Finais (Rating: 1200-1400)**\n- [Intermediário Avançado (1200-1400) 🎯♟️\n\n📝 **Objetivo**: Melhorar a técnica em finais de peças menores e aprender as ideias de conversão em finais complexos.\n\n🎓 **Prática**:\n- Estude os finais de Torre e Cavalo contra Rei e como dominar o Rei adversário.\n- Aprofunde-se nas ideias de atacar pontos fracos no final do jogo.\n\n🔑 **Princípios**:\n- Em finais de torre, tenha sempre uma ideia clara sobre como restringir o Rei adversário e apoiar seus peões.\n\n⏱️ **Atividade**:\n- Jogue finais de Torre e Peão contra Peão, concentrando-se em como forçar a vitória.\n\n⚠️ **Dica**:\n- Sempre faça o seu Rei avançar com segurança, criando espaço para os peões passarem. ⚔️\n\n📚 **Livro recomendado**:\n- 'Finais de Xadrez: Técnica e Prática' de Mark Dvoretsky 📖]"
        elif rating < 1600:
            return f"📌 **Treino de Finais (Rating: 1400-1600)**\n- [Avançado (1400-1600) 💡♟️\n\n📝 **Objetivo**: Estudar finais mais complexos e aprender a usar o conceito de zugzwang e outros métodos avançados.\n\n🎓 **Prática**:\n- Estude os finais de peças menores (Torre + Bispo ou Cavalo) contra Rei.\n- Aprenda as técnicas de promoção de peão em posições mais complicadas.\n\n🔑 **Princípios**:\n- Atente-se para a correta colocação do Rei e das peças menores no final.\n\n⏱️ **Atividade**:\n- Jogue finais de Torre e Bispo/Cavalo contra Rei.\n\n⚠️ **Dica**:\n- Tenha sempre a mobilidade do Rei em mente e evite posições passivas. 🔒\n\n📚 **Livro recomendado**:\n- 'Os Finais de Xadrez' de José Raúl Capablanca 📚]"
        elif rating < 1800:
            return f"📌 **Treino de Finais (Rating: 1600-1800)**\n- [Muito Avançado (1600-1800) 🏅♟️\n\n📝 **Objetivo**: Aprofundar-se nas técnicas de finais, focando em conceitos como os finais de torre e peões contra peças menores.\n\n🎓 **Prática**:\n- Estude os finais de Torre contra Torre e como dominar a posição em finais de várias peças.\n- Aprenda as ideias de ganho por oposição em finais avançados.\n\n🔑 **Princípios**:\n- Aplique ideias de simplificação e centralização de peças para dominar os finais de jogo.\n\n⏱️ **Atividade**:\n- Jogue finais complexos de Torre e Peão contra Torre e Peão.\n\n⚠️ **Dica**:\n- Estude a técnica de forçar uma vitória em finais com material em equilíbrio. 💎\n\n📚 **Livro recomendado**:\n- 'Finais: A Arte de Ganhar' de Yuri Averbakh 📖]"
        elif rating < 2000:
            return f"📌 **Treino de Finais (Rating: 1800-2000)**\n- [Especialista (1800-2000) 💪♟️\n\n📝 **Objetivo**: Aperfeiçoar os cálculos de finais em posições desequilibradas e aplicar as ideias estratégicas para alcançar a vitória.\n\n🎓 **Prática**:\n- Estude os finais de torre contra peão e como bloquear a promoção do peão adversário.\n- Analise os finais de Rei e Peão contra Rei e como usar o conceito de oposição para alcançar a vitória.\n\n🔑 **Princípios**:\n- Aplique a técnica de simplificação e aproveite as vantagens de materiais superiores.\n\n⏱️ **Atividade**:\n- Jogue finais de Torre e Peão contra Rei, visando o controle de espaço e a promoção do peão.\n\n⚠️ **Dica**:\n- Use o Rei como uma ferramenta para atacar, sempre que possível. ⚔️\n\n📚 **Livro recomendado**:\n- 'Finais de Xadrez' de Mikhail Shereshevsky 📚]"
        elif rating < 2200:
            return f"📌 **Treino de Finais (Rating: 2000-2200)**\n- [Mestre (2000-2200) 🏆♟️\n\n📝 **Objetivo**: Refine a habilidade de calcular variantes de finais e realizar transições de posições complexas para uma vantagem clara.\n\n🎓 **Prática**:\n- Estude finais avançados como Torre + Peão contra Torre + Peão e as posições de oposição.\n- Melhore a técnica em finais de Rei e Peão contra Rei. Concentre-se na técnica e no tempo. 🕰️\n\n🔑 **Princípios**:\n- Entenda a dinâmica dos peões passados e aprenda como bloqueá-los ou promovê-los.\n\n⏱️ **Atividade**:\n- Jogue finais de Torre contra Peão em posições difíceis e calcule até o último movimento.\n\n⚠️ **Dica**:\n- Sempre se concentre em colocar seu Rei na melhor posição para apoiar os peões. 👑\n\n📚 **Livro recomendado**:\n- 'Finais de Xadrez: Técnica e Tática' de Jonathan Tisdall 📖]"
        else:
            return f"📌 **Treino de Finais (Rating: 2200+)**\n- [Grande Mestre (2200+) 🏅♟️\n\n📝 **Objetivo**: Aprofundar-se em finais complexos com várias peças e aumentar a precisão nos cálculos de variantes no final.\n\n🎓 **Prática**:\n- Estude os finais de peças menores em posições abertas e as técnicas de mestre finalista.\n- Aprofunde-se nas técnicas de defesa ativa e contra-ataque em finais difíceis.\n\n🔑 **Princípios**:\n- Aplique uma combinação precisa de técnica e estratégia para dominar os finais avançados.\n\n⏱️ **Atividade**:\n- Jogue finais avançados de Torre e Peão contra Torre e Peão e calcule todas as variantes.\n\n⚠️ **Dica**:\n- Avalie cada posição com precisão antes de executar, é hora de usar toda a sua experiência. 💎\n\n📚 **Livro recomendado**:\n- 'Finais: Te]"
        pass

    if objetivo == "Tática":
        if rating < 1000:
            return f"📌 **Treino de Tática (Rating: 0-1000)**\n- [Iniciante (0-999) 🌱♟️\n\n📝 **Objetivo**: Começar a identificar táticas simples e aprender os fundamentos das combinações.\n\n🎓 **Prática**:\n- Estude o conceito de ataque duplo (duas ameaças simultâneas) e garanta que saiba como usar a tática de garfo.\n- Pratique a captura de peças com ataques duplos em posições simples.\n\n🔑 **Princípios**:\n- Tente sempre identificar a peça mais valiosa do seu oponente e pense em como atacá-la com a sua peça mais próxima.\n\n⏱️ **Atividade**:\n- Resolva exercícios simples de táticas de garfo, cravada e ataque duplo.\n\n⚠️ **Dica**:\n- Sempre que seu oponente fizer um movimento, pense: Qual peça dele está vulnerável? 👀\n\n📚 **Livro recomendado**:\n- 'Xadrez Para Crianças' de Murray Chandler 📖]"
        elif rating < 1200:
            return f"📌 **Treino de Tática (Rating: 1000-1200)**\n- [Intermediário (1000-1200) 🧠♟️\n\n📝 **Objetivo**: Começar a combinar várias táticas em uma sequência e aprender a visualizar mais de uma jogada à frente.\n\n🎓 **Prática**:\n- Estude a tática de cravada, ataque duplo e as combinações que resultam em ganho material.\n- Comece a explorar combinações de táticas mais complexas.\n\n🔑 **Princípios**:\n- Pense sempre em como combinar ataques simultâneos e táticas de peças para capturar peças adversárias.\n\n⏱️ **Atividade**:\n- Resolva exercícios envolvendo ataque duplo e cravada.\n\n⚠️ **Dica**:\n- Ao analisar o tabuleiro, pergunte-se: Onde estão as fraquezas do meu oponente?"
        elif rating < 1400:
            return f"📌 **Treino de Tática (Rating: 1200-1400)**\n- [Intermediário Avançado (1200-1400) 🎯♟️\n\n📝 **Objetivo**: Aprofundar-se em táticas mais complexas, como garfos em múltiplas peças e ataques forçados.\n\n🎓 **Prática**:\n- Estude e pratique o uso de garfos, cravadas, e descobertas, com foco em movimentos duplos e ataques rápidos.\n- Comece a combinar táticas de maneira criativa.\n\n🔑 **Princípios**:\n- Busque sempre uma combinação de táticas que forcem o oponente a perder material ou a entrar em uma posição desvantajosa.\n\n⏱️ **Atividade**:\n- Resolva exercícios avançados que envolvem combinações rápidas de táticas e ataques forçados.\n\n⚠️ **Dica**:\n- Fique atento a qualquer peça mal posicionada do oponente. Às vezes, uma boa combinação pode surgir de um erro simples. 🧐\n\n📚 **Livro recomendado**:\n- 'Como Resolver Táticas de Xadrez' de Gary Lane 📖]"
        elif rating < 1600:
            return f"📌 **Treino de Tática (Rating: 1400-1600)**\n- [Avançado (1400-1600) 💡♟️\n\n📝 **Objetivo**: Melhorar a visão tática em posições mais dinâmicas e aprender a utilizar táticas defensivas.\n\n🎓 **Prática**:\n- Estude o conceito de interceptação, táticas defensivas e combinações complexas para atacar várias peças ao mesmo tempo.\n- Combine várias táticas, como o ataque duplo e a cravada, para criar problemas para o oponente.\n\n🔑 **Princípios**:\n- Pense em todos os tipos de táticas possíveis, incluindo aquelas que não envolvem capturar uma peça diretamente, mas sim forçar um erro.\n\n⏱️ **Atividade**:\n- Resolva exercícios de combinações complexas e defenda-se de ataques enquanto contra-ataca.\n\n⚠️ **Dica**:\n- Ao analisar o tabuleiro, pergunte-se: Como posso forçar a vitória usando táticas? 🏆\n\n📚 **Livro recomendado**:\n- 'Táticas de Xadrez: Prática e Teoria' de Paul Keres 📖]"
        elif rating < 1800:
            return f"📌 **Treino de Tática (Rating: 1600-1800)**\n- [Muito Avançado (1600-1800) 🏅♟️\n\n📝 **Objetivo**: Aperfeiçoar as táticas avançadas e desenvolver a habilidade de calcular várias jogadas à frente.\n\n🎓 **Prática**:\n- Estude a tática de ataque descoberto, garfo duplo e ataque direto com sacrifícios.\n- Explore como fazer um sacrifício de peça para obter uma vantagem decisiva.\n\n🔑 **Princípios**:\n- Use combinações de táticas para surpreender o oponente e gerar um ataque rápido e eficaz.\n\n⏱️ **Atividade**:\n- Resolva exercícios que envolvam sacrifícios e ataques combinados.\n\n⚠️ **Dica**:\n- Concentre-se na ideia de táticas de sacrifício para mudar o curso da partida. ⚔️\n\n📚 **Livro recomendado**:\n- 'Xadrez Tático: A Arte do Ataque' de Alexander Kotov 📖]"
        elif rating < 2000:
            return f"📌 **Treino de Tática (Rating: 1800-2000)**\n- [Especialista (1800-2000) 💪♟️\n\n📝 **Objetivo**: Aprimorar o cálculo de variantes táticas e começar a dominar o uso de combinações de ataques para obter vantagem decisiva.\n\n🎓 **Prática**:\n- Estude as combinações de táticas mais avançadas, como o ataque de sacrifício para abrir linhas de ataque.\n- Encontre combinações táticas que envolvem vários tipos de ataque ao mesmo tempo.\n\n🔑 **Princípios**:\n- Cada jogada deve ser calculada com precisão, considerando táticas de médio e longo prazo.\n\n⏱️ **Atividade**:\n- Resolva exercícios de táticas complexas com sacrifícios e combinações de peças.\n\n⚠️ **Dica**:\n- Sempre visualize o plano tático do oponente e procure contra-ataques que forcem erros.🧐\n\n📚 **Livro recomendado**:\n- 'Xadrez: Táticas Avançadas' de John Nunn 📖]"
        elif rating < 2200:
            return f"📌 **Treino de Tática (Rating: 2000-2200)**\n- [Mestre (2000-2200) 🏆♟️\n\n📝 **Objetivo**: Dominar a técnica de táticas avançadas e aprender a calcular com precisão as linhas táticas mais complexas.\n\n🎓 **Prática**:\n- Estude as táticas de ataque forçado e defina o conceito de motivo tático em várias posições.\n- Treine o uso de táticas em finais de jogo complexos, como dar xeque-mate com sacrifícios.\n\n🔑 **Princípios**:\n- Considere cada possibilidade de ataque e defesa com foco na precisão e no tempo disponível.\n\n⏱️ **Atividade**:\n- Resolva exercícios envolvendo combinação de táticas em diferentes fases do jogo.\n\n⚠️ **Dica**:\n- Tente visualizar todas as possibilidades de táticas antes de executar. Isso pode mudar o jogo a seu favor. 💥\n\n📚 **Livro recomendado**:\n- 'Mastering Chess Tactics' de Daniel King 📖]"
        else:
            return f"📌 **Treino de Tática (Rating: 2200+)**\n- [Grande Mestre (2200+) 🏅♟️\n\n📝 **Objetivo**: Refinar a técnica de táticas com foco em combinações complexas e sequências rápidas para vencer o adversário.\n\n🎓 **Prática**:\n- Estude e calcule combinações táticas de várias peças, sacrifícios e ataques rápidos que levam à vitória.\n- Aplique táticas avançadas em situações de tempo limitado.\n\n🔑 **Princípios**:\n- A precisão nos cálculos e a rapidez em identificar as melhores combinações são cruciais em um nível de grande mestre.\n\n⏱️ **Atividade**:\n- Resolva exercícios de combinação tática extremamente desafiadores e jogue partidas rápidas para aplicar o conhecimento.\n\n⚠️ **Dica**:\n- Sempre tenha um plano de contingência ao executar uma combinação tática, garantindo que você possa reagir rapidamente a qualquer movimento adversário. 🔄\n\n📚 **Livro recomendado**:\n- 'Tactical Chess Mastery' de Mark Dvoretsky 📖]"
        pass

    return "⚠️ Objetivo não reconhecido. Por favor, reinicie o bot com /start."

def main():
    app = Application.builder().token(TOKEN).build()

    app.add_handler(CommandHandler("start", start))
    app.add_handler(CallbackQueryHandler(button))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, recebe_mensagem))

    print("Bot está rodando...")
    app.run_polling()

if __name__ == "__main__":
    main()
